apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels: {{.Values.podSelector.bot | toYaml | nindent 6}}
  template:
    metadata:
      labels: {{.Values.podSelector.bot | toYaml | nindent 8}}
    spec:
      containers:
        - name: discord-bot-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: discord-bot-config